import { FamilyMember, LineageInfo, LineageType } from '../types/family';

export const LINEAGES: Record<LineageType, LineageInfo> = {
  paternal: {
    key: 'paternal',
    label: '부친쪽 (친가)',
    shortLabel: '친가',
    clan: '경주 김씨 (慶州 金氏)',
    badgeColor: '#8b2020', // inkTheme.accentRed
    description: '본인 직계 친족 가계',
  },
  maternal: {
    key: 'maternal',
    label: '모친쪽 (외가)',
    shortLabel: '외가',
    clan: '전주 이씨 (全州 李氏)',
    badgeColor: '#1a3d2e', // inkTheme.accentPine
    description: '어머니 본가 가계',
  },
  inlaw_paternal: {
    key: 'inlaw_paternal',
    label: '사돈댁 부친쪽 (처가 친가)',
    shortLabel: '사돈(친가)',
    clan: '동래 정씨 (東萊 鄭氏)',
    badgeColor: '#7a5c1e', // inkTheme.accentGold
    description: '배우자 아버지 본가 가계',
  },
  inlaw_maternal: {
    key: 'inlaw_maternal',
    label: '사돈댁 모친쪽 (처가 외가)',
    shortLabel: '사돈(외가)',
    clan: '남원 양씨 (南原 梁氏)',
    badgeColor: '#4a4a44', // inkTheme.ink3
    description: '배우자 어머니 본가 가계',
  },
};

export const INITIAL_FAMILY_DATA: FamilyMember[] = [
  // ==========================================
  // 1. 부친쪽 (친가 - 경주 김씨)
  // ==========================================
  // 1대: 조부모
  {
    id: 'pat-1-1',
    name: '김진호',
    hanja: '金鎭浩',
    gender: 'M',
    generation: 1,
    lineage: 'paternal',
    relationship: '조부 (친할아버지)',
    clan: '경주 김씨',
    birthDate: '1935-03-15',
    deathDate: '2018-11-20',
    isAlive: false,
    spouseId: 'pat-1-2',
    memo: '경주 김씨 판도판서공파 27세손. 교직 35년 퇴임.',
  },
  {
    id: 'pat-1-2',
    name: '박순자',
    hanja: '朴順子',
    gender: 'F',
    generation: 1,
    lineage: 'paternal',
    relationship: '조모 (친할머니)',
    clan: '밀양 박씨',
    birthDate: '1938-08-22',
    isAlive: true,
    spouseId: 'pat-1-1',
    phone: '010-3412-8811',
    lastContactDate: '2026-08-01',
    contactCycleDays: 14,
    memo: '현재 안동 본가 거주. 건강 양호.',
  },
  // 2대: 부친 및 백부/고모
  {
    id: 'pat-2-1',
    name: '김영호',
    hanja: '金英浩',
    gender: 'M',
    generation: 2,
    lineage: 'paternal',
    relationship: '큰아버지 (백부)',
    clan: '경주 김씨',
    birthDate: '1959-05-10',
    isAlive: true,
    parentIds: ['pat-1-1', 'pat-1-2'],
    phone: '010-9182-4411',
    lastContactDate: '2026-07-15',
    contactCycleDays: 30,
    memo: '대구 거주. 종친회 총무 역임.',
  },
  {
    id: 'pat-2-2',
    name: '김영수',
    hanja: '金英洙',
    gender: 'M',
    generation: 2,
    lineage: 'paternal',
    relationship: '아버지 (부친)',
    clan: '경주 김씨',
    birthDate: '1962-02-18',
    isAlive: true,
    parentIds: ['pat-1-1', 'pat-1-2'],
    spouseId: 'mat-2-1',
    phone: '010-5231-7788',
    lastContactDate: '2026-09-08',
    contactCycleDays: 7,
    memo: '서울 거주. 매주 주말 안부 전화.',
  },
  {
    id: 'pat-2-3',
    name: '김영숙',
    hanja: '金英淑',
    gender: 'F',
    generation: 2,
    lineage: 'paternal',
    relationship: '고모',
    clan: '경주 김씨',
    birthDate: '1965-10-03',
    isAlive: true,
    parentIds: ['pat-1-1', 'pat-1-2'],
    phone: '010-2399-6120',
    lastContactDate: '2026-06-20',
    contactCycleDays: 45,
    memo: '부산 거주. 화훼업 종사.',
  },
  // 3대: 본인 및 동생들
  {
    id: 'pat-3-1',
    name: '김준혁',
    hanja: '金準赫',
    gender: 'M',
    generation: 3,
    lineage: 'paternal',
    relationship: '본인',
    clan: '경주 김씨 29세손',
    birthDate: '1990-04-25',
    isAlive: true,
    parentIds: ['pat-2-2', 'mat-2-1'],
    spouseId: 'inlaw-pat-3-1',
    phone: '010-1234-5678',
    lastContactDate: '2026-09-11',
    contactCycleDays: 1,
    memo: '족보 앱 관리자 (나)',
  },
  {
    id: 'pat-3-2',
    name: '김민혁',
    hanja: '金珉赫',
    gender: 'M',
    generation: 3,
    lineage: 'paternal',
    relationship: '남동생',
    clan: '경주 김씨 29세손',
    birthDate: '1993-11-14',
    isAlive: true,
    parentIds: ['pat-2-2', 'mat-2-1'],
    phone: '010-8877-3322',
    lastContactDate: '2026-09-05',
    contactCycleDays: 14,
    memo: '판교 IT 기업 근무.',
  },
  {
    id: 'pat-3-3',
    name: '김지우',
    hanja: '金智友',
    gender: 'F',
    generation: 3,
    lineage: 'paternal',
    relationship: '여동생',
    clan: '경주 김씨 29세손',
    birthDate: '1996-07-08',
    isAlive: true,
    parentIds: ['pat-2-2', 'mat-2-1'],
    phone: '010-4455-6677',
    lastContactDate: '2026-09-02',
    contactCycleDays: 14,
    memo: '디자이너 프리랜서 활동.',
  },
  // 4대: 자녀
  {
    id: 'pat-4-1',
    name: '김도윤',
    hanja: '金道潤',
    gender: 'M',
    generation: 4,
    lineage: 'paternal',
    relationship: '장남 (아들)',
    clan: '경주 김씨 30세손',
    birthDate: '2020-05-12',
    isAlive: true,
    parentIds: ['pat-3-1', 'inlaw-pat-3-1'],
    memo: '유치원 재학 중.',
  },
  {
    id: 'pat-4-2',
    name: '김하은',
    hanja: '金夏恩',
    gender: 'F',
    generation: 4,
    lineage: 'paternal',
    relationship: '장녀 (딸)',
    clan: '경주 김씨 30세손',
    birthDate: '2023-09-20',
    isAlive: true,
    parentIds: ['pat-3-1', 'inlaw-pat-3-1'],
    memo: '어린이집 재학 중.',
  },

  // ==========================================
  // 2. 모친쪽 (외가 - 전주 이씨)
  // ==========================================
  // 1대: 외조부모
  {
    id: 'mat-1-1',
    name: '이성한',
    hanja: '李成漢',
    gender: 'M',
    generation: 1,
    lineage: 'maternal',
    relationship: '외할아버지 (외조부)',
    clan: '전주 이씨',
    birthDate: '1937-01-19',
    isAlive: true,
    spouseId: 'mat-1-2',
    phone: '010-6712-3344',
    lastContactDate: '2026-07-28',
    contactCycleDays: 21,
    memo: '전주 본가 거주. 서예 취미.',
  },
  {
    id: 'mat-1-2',
    name: '권정자',
    hanja: '權貞子',
    gender: 'F',
    generation: 1,
    lineage: 'maternal',
    relationship: '외할머니 (외조모)',
    clan: '안동 권씨',
    birthDate: '1941-04-09',
    isAlive: true,
    spouseId: 'mat-1-1',
    phone: '010-6712-3345',
    lastContactDate: '2026-07-28',
    contactCycleDays: 21,
    memo: '전주 본가 거주.',
  },
  // 2대: 모친 및 외숙/이모
  {
    id: 'mat-2-1',
    name: '이은경',
    hanja: '李恩敬',
    gender: 'F',
    generation: 2,
    lineage: 'maternal',
    relationship: '어머니 (모친)',
    clan: '전주 이씨',
    birthDate: '1964-06-30',
    isAlive: true,
    parentIds: ['mat-1-1', 'mat-1-2'],
    spouseId: 'pat-2-2',
    phone: '010-5231-7789',
    lastContactDate: '2026-09-09',
    contactCycleDays: 7,
    memo: '서울 거주.',
  },
  {
    id: 'mat-2-2',
    name: '이은철',
    hanja: '李恩哲',
    gender: 'M',
    generation: 2,
    lineage: 'maternal',
    relationship: '외삼촌 (외숙)',
    clan: '전주 이씨',
    birthDate: '1967-09-15',
    isAlive: true,
    parentIds: ['mat-1-1', 'mat-1-2'],
    phone: '010-7822-1980',
    lastContactDate: '2026-07-10',
    contactCycleDays: 45,
    memo: '대전 거주. 연구원 재직.',
  },
  {
    id: 'mat-2-3',
    name: '이은미',
    hanja: '李恩美',
    gender: 'F',
    generation: 2,
    lineage: 'maternal',
    relationship: '이모',
    clan: '전주 이씨',
    birthDate: '1971-12-05',
    isAlive: true,
    parentIds: ['mat-1-1', 'mat-1-2'],
    phone: '010-4491-0023',
    lastContactDate: '2026-08-15',
    contactCycleDays: 30,
    memo: '수원 거주.',
  },
  // 3대: 외사촌
  {
    id: 'mat-3-1',
    name: '이시우',
    hanja: '李時宇',
    gender: 'M',
    generation: 3,
    lineage: 'maternal',
    relationship: '외사촌동생',
    clan: '전주 이씨',
    birthDate: '1995-03-21',
    isAlive: true,
    parentIds: ['mat-2-2'],
    phone: '010-9901-2244',
    lastContactDate: '2026-08-20',
    contactCycleDays: 60,
    memo: '대학원 박사과정.',
  },

  // ==========================================
  // 3. 사돈댁 부친쪽 (처가 친가 - 동래 정씨)
  // ==========================================
  // 1대: 처조부모
  {
    id: 'inlaw-pat-1-1',
    name: '정태원',
    hanja: '鄭泰元',
    gender: 'M',
    generation: 1,
    lineage: 'inlaw_paternal',
    relationship: '처조부 (사돈할아버지)',
    clan: '동래 정씨',
    birthDate: '1934-02-10',
    deathDate: '2020-03-18',
    isAlive: false,
    spouseId: 'inlaw-pat-1-2',
    memo: '동래 정씨 직제학공파.',
  },
  {
    id: 'inlaw-pat-1-2',
    name: '윤명숙',
    hanja: '尹明淑',
    gender: 'F',
    generation: 1,
    lineage: 'inlaw_paternal',
    relationship: '처조모 (사돈할머니)',
    clan: '파평 윤씨',
    birthDate: '1939-11-25',
    isAlive: true,
    spouseId: 'inlaw-pat-1-1',
    phone: '010-7711-2299',
    lastContactDate: '2026-07-05',
    contactCycleDays: 30,
    memo: '부산 거주. 명절에 인사드림.',
  },
  // 2대: 장인 및 처백부
  {
    id: 'inlaw-pat-2-1',
    name: '정우진',
    hanja: '鄭宇鎭',
    gender: 'M',
    generation: 2,
    lineage: 'inlaw_paternal',
    relationship: '장인어른 (시아버지/빙부)',
    clan: '동래 정씨',
    birthDate: '1961-04-14',
    isAlive: true,
    parentIds: ['inlaw-pat-1-1', 'inlaw-pat-1-2'],
    spouseId: 'inlaw-mat-2-1',
    phone: '010-3344-9900',
    lastContactDate: '2026-08-25',
    contactCycleDays: 14,
    memo: '분당 거주. 주말 골프 및 등산.',
  },
  {
    id: 'inlaw-pat-2-2',
    name: '정우택',
    hanja: '鄭宇澤',
    gender: 'M',
    generation: 2,
    lineage: 'inlaw_paternal',
    relationship: '처백부 (처가 큰아버지)',
    clan: '동래 정씨',
    birthDate: '1958-09-02',
    isAlive: true,
    parentIds: ['inlaw-pat-1-1', 'inlaw-pat-1-2'],
    phone: '010-8822-1100',
    lastContactDate: '2026-05-10',
    contactCycleDays: 60,
    memo: '울산 거주. 사업 경영.',
  },
  // 3대: 배우자 및 처남
  {
    id: 'inlaw-pat-3-1',
    name: '정서연',
    hanja: '鄭瑞娟',
    gender: 'F',
    generation: 3,
    lineage: 'inlaw_paternal',
    relationship: '배우자 (아내)',
    clan: '동래 정씨',
    birthDate: '1992-08-17',
    isAlive: true,
    parentIds: ['inlaw-pat-2-1', 'inlaw-mat-2-1'],
    spouseId: 'pat-3-1',
    phone: '010-9988-7766',
    lastContactDate: '2026-09-12',
    contactCycleDays: 1,
    memo: '아내. 초등학교 교사.',
  },
  {
    id: 'inlaw-pat-3-2',
    name: '정서진',
    hanja: '鄭瑞鎭',
    gender: 'M',
    generation: 3,
    lineage: 'inlaw_paternal',
    relationship: '처남',
    clan: '동래 정씨',
    birthDate: '1995-12-03',
    isAlive: true,
    parentIds: ['inlaw-pat-2-1', 'inlaw-mat-2-1'],
    phone: '010-4433-2211',
    lastContactDate: '2026-08-18',
    contactCycleDays: 30,
    memo: '건축사사무소 근무.',
  },

  // ==========================================
  // 4. 사돈댁 모친쪽 (처가 외가 - 남원 양씨)
  // ==========================================
  // 1대: 처외조부모
  {
    id: 'inlaw-mat-1-1',
    name: '양기철',
    hanja: '梁基哲',
    gender: 'M',
    generation: 1,
    lineage: 'inlaw_maternal',
    relationship: '처외조부 (처가 외할아버지)',
    clan: '남원 양씨',
    birthDate: '1936-07-29',
    isAlive: true,
    spouseId: 'inlaw-mat-1-2',
    phone: '010-5511-8822',
    lastContactDate: '2026-06-15',
    contactCycleDays: 45,
    memo: '강릉 본가 거주. 농원 운영.',
  },
  {
    id: 'inlaw-mat-1-2',
    name: '김복순',
    hanja: '金福順',
    gender: 'F',
    generation: 1,
    lineage: 'inlaw_maternal',
    relationship: '처외조모 (처가 외할머니)',
    clan: '광산 김씨',
    birthDate: '1940-05-14',
    isAlive: true,
    spouseId: 'inlaw-mat-1-1',
    phone: '010-5511-8823',
    lastContactDate: '2026-06-15',
    contactCycleDays: 45,
    memo: '강릉 본가 거주.',
  },
  // 2대: 장모 및 처외숙/처이모
  {
    id: 'inlaw-mat-2-1',
    name: '양혜정',
    hanja: '梁惠貞',
    gender: 'F',
    generation: 2,
    lineage: 'inlaw_maternal',
    relationship: '장모님 (시어머니/빙모)',
    clan: '남원 양씨',
    birthDate: '1963-09-08',
    isAlive: true,
    parentIds: ['inlaw-mat-1-1', 'inlaw-mat-1-2'],
    spouseId: 'inlaw-pat-2-1',
    phone: '010-3344-9901',
    lastContactDate: '2026-08-28',
    contactCycleDays: 14,
    memo: '분당 거주. 손주들 자주 돌봐주심.',
  },
  {
    id: 'inlaw-mat-2-2',
    name: '양동현',
    hanja: '梁東賢',
    gender: 'M',
    generation: 2,
    lineage: 'inlaw_maternal',
    relationship: '처외숙 (처가 외삼촌)',
    clan: '남원 양씨',
    birthDate: '1966-03-22',
    isAlive: true,
    parentIds: ['inlaw-mat-1-1', 'inlaw-mat-1-2'],
    phone: '010-6677-1122',
    lastContactDate: '2026-04-12',
    contactCycleDays: 60,
    memo: '원주 거주. 자영업.',
  },
  {
    id: 'inlaw-mat-2-3',
    name: '양숙경',
    hanja: '梁淑卿',
    gender: 'F',
    generation: 2,
    lineage: 'inlaw_maternal',
    relationship: '처이모 (처가 이모)',
    clan: '남원 양씨',
    birthDate: '1970-11-19',
    isAlive: true,
    parentIds: ['inlaw-mat-1-1', 'inlaw-mat-1-2'],
    phone: '010-2211-9988',
    lastContactDate: '2026-05-20',
    contactCycleDays: 60,
    memo: '인천 거주.',
  },
];

// Helper Functions
export function getDaysSinceContact(dateStr?: string): number {
  if (!dateStr) return 999;
  const target = new Date(dateStr);
  const now = new Date('2026-09-12'); // 기준 현재 시각
  const diffTime = Math.abs(now.getTime() - target.getTime());
  return Math.floor(diffTime / (1000 * 60 * 60 * 24));
}

export function getUrgentCareMembers(members: FamilyMember[] = INITIAL_FAMILY_DATA): Array<FamilyMember & { daysPassed: number; isOverdue: boolean }> {
  return members
    .filter((m) => m.isAlive && m.id !== 'pat-3-1' && m.id !== 'inlaw-pat-3-1') // 본인/배우자 제외
    .map((m) => {
      const daysPassed = getDaysSinceContact(m.lastContactDate);
      const cycle = m.contactCycleDays || 30;
      return {
        ...m,
        daysPassed,
        isOverdue: daysPassed >= cycle,
      };
    })
    .sort((a, b) => b.daysPassed - a.daysPassed);
}